=== haijunsu-osu/linkage2d_json/planar_linkage.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.org/planar_linkage.schema.json",
  "title": "Planar Linkage",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "id",
    "name",
    "type",
    "unit_length",
    "unit_angle",
    "convention",
    "links",
    "joints"
  ],
  "properties": {
    "version": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "const": "planar_mechanism"
    },
    "unit_length": {
      "type": "string",
      "enum": [
        "mm",
        "cm",
        "m",
        "in",
        "px"
      ]
    },
    "unit_angle": {
      "type": "string",
      "enum": [
        "deg",
        "rad"
      ]
    },
    "convention": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "world_frame": {
          "type": "string"
        }
      }
    },
    "links": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/link"
      }
    },
    "joints": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/joint"
      }
    }
  },
  "$defs": {
    "pose": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "position",
        "angle"
      ],
      "properties": {
        "position": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 2,
          "maxItems": 2
        },
        "angle": {
          "type": "number"
        }
      }
    },
    "point": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "position"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "position": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "direction": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "angle"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "angle": {
          "type": "number"
        }
      }
    },
    "line": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "point_ids"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "point_ids": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "circle": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "center_point_id",
        "radius"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "center_point_id": {
          "type": "string"
        },
        "radius": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "arc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "center_point_id",
        "radius",
        "start_angle",
        "end_angle",
        "direction"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "center_point_id": {
          "type": "string"
        },
        "radius": {
          "type": "number",
          "minimum": 0
        },
        "start_angle": {
          "type": "number"
        },
        "end_angle": {
          "type": "number"
        },
        "direction": {
          "type": "string",
          "enum": [
            "ccw",
            "cw"
          ]
        }
      }
    },
    "link": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "isGrounded",
        "pose",
        "points",
        "directions",
        "lines",
        "circles",
        "arcs"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "isGrounded": {
          "type": "boolean"
        },
        "pose": {
          "$ref": "#/$defs/pose"
        },
        "points": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/point"
          },
          "uniqueItems": true
        },
        "directions": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/direction"
          },
          "uniqueItems": true
        },
        "lines": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/line"
          },
          "uniqueItems": true
        },
        "circles": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/circle"
          },
          "uniqueItems": true
        },
        "arcs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/arc"
          },
          "uniqueItems": true
        }
      }
    },
    "revolute_joint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "type",
        "parent",
        "point_id_parent",
        "child",
        "point_id_child"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "const": "revolute"
        },
        "parent": {
          "type": "string"
        },
        "child": {
          "type": "string"
        },
        "point_id_parent": {
          "type": "string"
        },
        "point_id_child": {
          "type": "string"
        }
      }
    },
    "prismatic_joint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "type",
        "parent",
        "axis_parent",
        "child",
        "point_id_child"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "const": "prismatic"
        },
        "parent": {
          "type": "string"
        },
        "child": {
          "type": "string"
        },
        "axis_parent": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "point_id",
            "direction_id"
          ],
          "properties": {
            "point_id": {
              "type": "string"
            },
            "direction_id": {
              "type": "string"
            }
          }
        },
        "point_id_child": {
          "type": "string"
        },
        "limits": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "min",
            "max"
          ],
          "properties": {
            "min": {
              "type": "number"
            },
            "max": {
              "type": "number"
            }
          }
        }
      }
    },
    "pin_in_slot_joint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "type",
        "parent",
        "line_id_parent",
        "child",
        "point_id_child"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "const": "pin-in-slot"
        },
        "parent": {
          "type": "string"
        },
        "child": {
          "type": "string"
        },
        "line_id_parent": {
          "type": "string"
        },
        "point_id_child": {
          "type": "string"
        }
      }
    },
    "gear_joint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "type",
        "parent",
        "child",
        "ratio",
        "phase_offset"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "const": "gear"
        },
        "parent": {
          "type": "string"
        },
        "child": {
          "type": "string"
        },
        "ratio": {
          "type": "number"
        },
        "phase_offset": {
          "type": "number"
        },
        "teeth_parent": {
          "type": "integer",
          "minimum": 1
        },
        "teeth_child": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "weld_joint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "type",
        "parent",
        "child",
        "relative_pos",
        "relative_angle"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "const": "weld"
        },
        "parent": {
          "type": "string"
        },
        "child": {
          "type": "string"
        },
        "relative_pos": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 2,
          "maxItems": 2
        },
        "relative_angle": {
          "type": "number"
        }
      }
    },
    "joint": {
      "oneOf": [
        {
          "$ref": "#/$defs/revolute_joint"
        },
        {
          "$ref": "#/$defs/prismatic_joint"
        },
        {
          "$ref": "#/$defs/pin_in_slot_joint"
        },
        {
          "$ref": "#/$defs/gear_joint"
        },
        {
          "$ref": "#/$defs/weld_joint"
        }
      ]
    }
  }
}

=== haijunsu-osu/linkage2d_json/four_bar.json
{
  "version": "1.0",
  "id": "four_bar_example",
  "name": "Planar Four-Bar",
  "type": "planar_mechanism",
  "unit_length": "mm",
  "unit_angle": "deg",
  "convention": {
    "world_frame": "x-right, y-up, ccw-positive"
  },
  "links": [
    {
      "id": "L1",
      "name": "ground",
      "isGrounded": true,
      "pose": {
        "position": [
          0,
          0
        ],
        "angle": 0
      },
      "points": [
        {
          "id": "A",
          "name": "A",
          "position": [
            0,
            0
          ]
        },
        {
          "id": "D",
          "name": "D",
          "position": [
            300,
            0
          ]
        }
      ],
      "directions": [
        {
          "id": "ax0",
          "name": "x_axis",
          "angle": 0
        }
      ],
      "lines": [
        {
          "id": "AD",
          "name": "AD",
          "point_ids": [
            "A",
            "D"
          ]
        }
      ],
      "circles": [],
      "arcs": []
    },
    {
      "id": "L2",
      "name": "input",
      "isGrounded": false,
      "pose": {
        "position": [
          0,
          0
        ],
        "angle": 0
      },
      "points": [
        {
          "id": "A2",
          "name": "A2",
          "position": [
            0,
            0
          ]
        },
        {
          "id": "B",
          "name": "B",
          "position": [
            120,
            0
          ]
        }
      ],
      "directions": [],
      "lines": [],
      "circles": [],
      "arcs": []
    },
    {
      "id": "L3",
      "name": "coupler",
      "isGrounded": false,
      "pose": {
        "position": [
          0,
          0
        ],
        "angle": 0
      },
      "points": [
        {
          "id": "B3",
          "name": "B3",
          "position": [
            0,
            0
          ]
        },
        {
          "id": "C",
          "name": "C",
          "position": [
            150,
            0
          ]
        }
      ],
      "directions": [],
      "lines": [],
      "circles": [],
      "arcs": []
    },
    {
      "id": "L4",
      "name": "output",
      "isGrounded": false,
      "pose": {
        "position": [
          0,
          0
        ],
        "angle": 0
      },
      "points": [
        {
          "id": "C4",
          "name": "C4",
          "position": [
            0,
            0
          ]
        },
        {
          "id": "D4",
          "name": "D4",
          "position": [
            220,
            0
          ]
        }
      ],
      "directions": [],
      "lines": [],
      "circles": [],
      "arcs": []
    }
  ],
  "joints": [
    {
      "id": "R1",
      "name": "A_rev",
      "type": "revolute",
      "parent": "L1",
      "point_id_parent": "A",
      "child": "L2",
      "point_id_child": "A2"
    },
    {
      "id": "R2",
      "name": "B_rev",
      "type": "revolute",
      "parent": "L2",
      "point_id_parent": "B",
      "child": "L3",
      "point_id_child": "B3"
    },
    {
      "id": "R3",
      "name": "C_rev",
      "type": "revolute",
      "parent": "L3",
      "point_id_parent": "C",
      "child": "L4",
      "point_id_child": "C4"
    },
    {
      "id": "R4",
      "name": "D_rev",
      "type": "revolute",
      "parent": "L1",
      "point_id_parent": "D",
      "child": "L4",
      "point_id_child": "D4"
    }
  ]
}

=== haijunsu-osu/linkage2d_json/crank_pin_in_slot.json
{
  "version": "1",
  "id": "crank_slider_slot",
  "type": "planar_mechanism",
  "convention": {},
  "name": "Crank-Slider with Pin-in-Slot Joint",
  "unit_length": "mm",
  "unit_angle": "deg",
  "links": [
    {
      "id": "ground",
      "name": "Ground",
      "isGrounded": true,
      "directions": [
        {"id": "x", "name": "X Axis", "angle": 0},
        {"id": "y", "name": "Y Axis", "angle": 90}
      ],
      "lines": [
        {"id": "ground_line", "name": "Ground Edge", "point_ids": ["A", "B"]},
        {"id": "slot_line", "name": "Slot", "point_ids": ["slot_start", "slot_end"]}
      ],
      "circles": [],
      "arcs": [],
      "pose": {"position": [0, 0], "angle": 0},
      "points": [
        {"id": "A", "name": "Ground A", "position": [0, 0]},
        {"id": "B", "name": "Ground B", "position": [100, 0]},
        {"id": "slot_start", "name": "Slot Start", "position": [50, 0]},
        {"id": "slot_end", "name": "Slot End", "position": [150, 0]}
      ]
    },
    {
      "id": "crank",
      "name": "Crank",
      "isGrounded": false,
      "directions": [
        {"id": "x", "name": "X Axis", "angle": 0},
        {"id": "y", "name": "Y Axis", "angle": 90}
      ],
      "lines": [
        {"id": "crank_line", "name": "Crank Arm", "point_ids": ["O", "C"]}
      ],
      "circles": [],
      "arcs": [],
      "pose": {"position": [50, 50], "angle": 40},
      "points": [
        {"id": "C", "name": "Crank End", "position": [40, 0]},
        {"id": "O", "name": "Crank Pivot", "position": [0, 0]}
      ]
    },
    {
      "id": "coupler",
      "name": "Coupler",
      "isGrounded": false,
      "directions": [
        {"id": "x", "name": "X Axis", "angle": 0},
        {"id": "y", "name": "Y Axis", "angle": 90}
      ],
      "lines": [
        {"id": "coupler_line", "name": "Coupler Bar", "point_ids": ["D", "E"]}
      ],
      "circles": [],
      "arcs": [],
      "pose": {"position": [0, 0], "angle": 0},
      "points": [
        {"id": "D", "name": "Coupler Pivot", "position": [0, 0]},
        {"id": "E", "name": "Slider Pin", "position": [100, 0]}
      ]
    }
  ],
  "joints": [
    {
  "id": "R1",
  "name": "Crank Pivot",
  "type": "revolute",
  "parent": "ground",
  "point_id_parent": "A",
  "child": "crank",
  "point_id_child": "O"
    },
    {
  "id": "R2",
  "name": "Coupler Pivot",
  "type": "revolute",
  "parent": "crank",
  "point_id_parent": "C",
  "child": "coupler",
  "point_id_child": "D"
    },
    {
      "id": "PIS1",
      "name": "Pin in Slot",
      "type": "pin-in-slot",
      "parent": "ground",
      "line_id_parent": "slot_line",
      "child": "coupler",
      "point_id_child": "E"
    }
  ]
}
